title: Apostolos Diamantakis
logo: /assets/img/CV PHOTO.jpg
"Customer Service Specialist at Teleperformance | Aspiring IT Professional | MBA & MSc in Applied Informatics | Passionate About Tech Innovation"show_downloads: true
theme: jekyll-theme-minimal
